### ISSUE TITLE
Починить равон

### ISSUE THREAD

**Issue by etepikina** [etepikina/Ravon#1]
![img_0536a7ce147e751a2b4127001ff2d26b](https://user-images.githubusercontent.com/45349904/50396352-29421500-079c-11e9-9095-3403c5c9367d.jpg)

**Comment by tepikin** [comment]
![image](https://user-images.githubusercontent.com/1471609/56941257-99431c00-6b3d-11e9-9f35-80e5c3d7ca79.png)
